inputs: 
  serviceAccountKey:
    required: true 
    type: string

runs:
  using: 'composite'

  steps:      
  - id: 'auth'
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v1'
    with:
      credentials_json: ${{ inputs.serviceAccountKey }}

  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v1'

  - name: 'Get Cloud SDK CLI Info'
    run: 'gcloud info'
    shell: bash

  - name: 'Install Terraform'
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: 1.5.7
