name: Infrastructure Deployment
run-name: ${{ github.actor }} is deploying infrastructure
on: [push]

jobs:
  Deploy-Dev:
    uses: ./.github/workflows/deploy_environment.yaml
    with:
      terraformModuleFolder: './terraform/environments/dev'
      githubEnvironment: 'Dev'
    secrets:
      serviceAccountKey: ${{ secrets.DEV_GOOGLE_SERVICE_ACCOUNT_KEY }}