name: Infrastructure Deployment
run-name: ${{ github.actor }} is deploying infrastructure
on: [push]

jobs:
  Deploy-Infrastructure:
    environment: Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/dev
    steps:
    - uses: 'actions/checkout@v3'

    - uses: ./.github/actions/setup_terraform
      with: 
        serviceAccountKey: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan
      