
on:
  workflow_call:
    inputs:
      terraformModuleFolder:
        required: true
        type: string
      githubEnvironmentName:
        required: true
        type: string
    secrets:
      serviceAccountKey:
        required: true

jobs:
  Terraform-Plan:
    name: 'Terraform Plan - ${{ inputs.githubEnvironmentName }}'
    environment: ${{ inputs.githubEnvironmentName }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraformModuleFolder }}
    steps:
    - uses: 'actions/checkout@v3'

    - uses: ./.github/actions/setup_terraform
      with: 
        serviceAccountKey: ${{ secrets.serviceAccountKey }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan
      