
on:
  workflow_call:
    inputs:
      terraformModuleFolder:
        required: true
        type: string
      githubEnvironmentName:
        required: true
        type: string
    secrets:
      serviceAccountKey:
        required: true

jobs:
  Terraform-Plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraformModuleFolder }}
    steps:
    - uses: 'actions/checkout@v3'

    - uses: ./.github/actions/setup_terraform
      with: 
        serviceAccountKey: ${{ secrets.serviceAccountKey }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ${{ inputs.terraformModuleFolder }}/tfplan
      
  Terraform-Apply:
    name: 'Terraform Apply'
    needs: Terraform-Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.githubEnvironmentName }}
    defaults:
      run:
        working-directory: ${{ inputs.terraformModuleFolder }}
    steps:
    - uses: 'actions/checkout@v3'

    - uses: ./.github/actions/setup_terraform
      with: 
        serviceAccountKey: ${{ secrets.serviceAccountKey }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Download Terraform Plan'
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: ${{ inputs.terraformModuleFolder }}

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan