name: Infrastructure Deployment
run-name: ${{ github.actor }} is deploying infrastructure
on: [push]
jobs:

  Deploy-Infrastructure:
    environment: Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/dev
    env: 
      PROJECT_ID: 'trapa-dev'
      BUCKET_NAME: 'terraform.trapa-dev.buntagon.com'
    steps:
    - uses: 'actions/checkout@v3'
        
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Get Cloud SDK CLI Info'
      run: 'gcloud info'

    - name: 'Install Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan

      